get http://localhost:3000/users  
###
get http://localhost:3000/users/6
###
POST http://localhost:3000/users
Content-Type: application/json

{
  
  "email": "maysoun@example.com",
  "userType": "TEACHER",
  "name": "mayssoun",
  "location": "montreal"
}
###
PATCH http://localhost:3000/users/6
Content-Type: application/json

{
  
  "location": "longueuil"
}
###
DELETE http://localhost:3000/users/9
