get http://localhost:3000/users  
###
get http://localhost:3000/users/6
###
POST http://localhost:3000/users
Content-Type: application/json

{
  
  "email": "maysoun@example.com",
  "userType": "TEACHER",
  "name": "mayssoun",
  "location": "montreal"
}
###
PUT http://localhost:3000/users/9
Content-Type: application/json

{
  
  "location": "longueuil"
}
###
DELETE http://localhost:3000/users/9
###
#####################################
get http://localhost:3000/books  
###
get http://localhost:3000/books/6
###
POST http://localhost:3000/books
Content-Type: application/json

{
  
  "title": "Le Petit Prince 1",
  "author": "Antoine de Saint-Exupéry",
  "category": "CHILDREN",
  "ageRange": "8-12",
  "schoolLevel": "primaire",
  "language": "fr"
}
###
DELETE http://localhost:3000/books/9